{
 "title": "API Performance",
 "tags": [
  "api",
  "performance"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Requests/sec by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(http_requests_total[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Latency p95 (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Error Rate % (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m])) * 100",
     "legendFormat": "Error Rate %"
    }
   ]
  },
  {
   "title": "Response Status Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency p99 by Endpoint (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, path)) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Average Request Size by Endpoint (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(rate(http_request_size_bytes[5m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}